name: Tests

on:
  push:
    branches:
      - master
      - dev-*
  pull_request:
    branches:
      - master
      - dev-*
      - fix-*
      - feature-*

jobs:
  build:
    environment: VeraBot
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Functionality-Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install distest
        run: python -m pip install distest

      - name: Login Heroku
        shell: bash
        run: |
          `cat >~/.netrc <<EOF
          machine api.heroku.com
              login $HEROKU_LOGIN
              password $HEROKU_API_KEY
          machine git.heroku.com
              login $HEROKU_LOGIN
              password $HEROKU_API_KEY
          EOF`
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_LOGIN: ${{ secrets.HEROKU_LOGIN }}

      - name: Set Remote Repository
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          heroku git:remote -a "$HEROKU_APP_NAME"

      - name: Push and Run Main Bot
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          git push heroku origin/$BRANCH_NAME:master --force
          heroku ps:scale worker=1
          sleep 20

      - name: Run Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_TARGET_ID: ${{ secrets.TEST_TARGET_ID }}
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          CHANNEL_ID: ${{ secrets.TEST_SERVER1_COMMANDS_CHANNEL_ID }}
          TEST_SERVER1_VERI_CHANNEL_ID: ${{ secrets.TEST_SERVER1_VERI_CHANNEL_ID }}
        run: python tests/server1_test.py "$TEST_TARGET_ID" "$TEST_TOKEN" -c "$CHANNEL_ID" --run all

      - name: End Bot
        if: always()
        run: heroku ps:scale worker=0
