name: CI

on:
  push:
    branches:
      - master
      - dev
    pull_request:
      - master
      - dev

jobs:
  build:
    continue-on-error: true
    environment: VeraBot
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Functionality-Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: install heroku
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - name: Run Main Bot  
        run: |
          echo "$HEROKU_LOGIN $HEROKU_PW" | heroku login -i
          heroku git:remote -a "$HEROKU_APP_NAME"
          git push heroku ${GITHUB_REF##*/}:master
          heroku ps:scale worker=1
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_LOGIN: ${{ secrets.HEROKU_LOGIN }}
          HEROKU_PW: ${{ secrets.HEROKU_PW }}


      - name: Run Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_TARGET_ID: ${{ secrets.TEST_TARGET_ID }}
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          CHANNEL_ID: ${{ secrets.TEST_SERVER1_COMMANDS_CHANNEL_ID}}
        run: python tests/tests.py #"$TEST_TARGET_ID" "$TEST_TOKEN" -c "$CHANNEL_ID"

      - name: End Bot
        run: heroku ps:scale worker=0